In [3]:
pwd

'C:\\Users\\Dppzee'

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("D:\Python code\CSV\heart_disease.csv")

In [5]:
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [8]:
df.head(50)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,...,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,...,No,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No
7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,No,...,No,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No
8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,Yes,...,Yes,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No
9,75.0,Male,144.0,252.0,Low,Yes,Yes,No,30.142149,No,...,Yes,Low,Medium,4.002662,High,199.0,96.0,10.005698,7.604357,No
10,36.0,Female,179.0,191.0,High,No,Yes,No,34.447618,No,...,No,Medium,High,9.151889,High,231.0,NaN,13.583347,13.783722,No
11,40.0,Female,134.0,296.0,High,No,Yes,Yes,31.739622,No,...,No,NaN,Medium,6.765162,Medium,109.0,139.0,6.694785,19.440650,No
12,28.0,Female,143.0,215.0,High,Yes,No,Yes,33.344017,No,...,Yes,Medium,Low,7.188455,Low,196.0,142.0,8.426725,11.146408,No
13,28.0,Female,134.0,191.0,High,Yes,No,No,19.422428,Yes,...,No,Low,Low,8.189629,Low,178.0,102.0,3.380839,17.478149,No
14,41.0,Female,150.0,187.0,High,No,Yes,No,37.387840,Yes,...,No,Medium,Low,9.624732,Low,343.0,124.0,10.051791,9.897205,No
15,70.0,Male,133.0,290.0,Medium,Yes,Yes,Yes,32.166488,No,...,Yes,Medium,Low,4.949260,Medium,397.0,155.0,4.620012,7.919947,No
16,53.0,Female,173.0,255.0,Medium,No,Yes,No,31.433878,Yes,...,No,Medium,Medium,4.427105,Medium,212.0,160.0,13.309069,9.784993,No
17,57.0,Female,133.0,245.0,Low,No,Yes,Yes,26.519301,No,...,No,Medium,High,4.731453,High,384.0,132.0,0.028436,14.306619,No
18,41.0,Male,125.0,219.0,Medium,Yes,Yes,No,18.618979,No,...,Yes,High,High,8.444345,Medium,346.0,106.0,7.176291,13.868994,No
19,20.0,Female,133.0,187.0,High,Yes,No,Yes,37.832158,Yes,...,Yes,NaN,High,4.775667,Low,290.0,144.0,12.472821,11.703830,No
20,39.0,Female,136.0,246.0,High,Yes,Yes,No,39.684635,No,...,Yes,Medium,High,7.005886,Low,380.0,124.0,4.407841,15.325098,No
21,70.0,Female,137.0,257.0,High,No,No,No,35.771306,Yes,...,Yes,Low,Low,8.238970,Medium,312.0,135.0,7.275610,8.566388,No
22,19.0,Female,139.0,268.0,Low,No,Yes,No,38.130862,Yes,...,Yes,High,High,8.276571,High,178.0,80.0,1.586211,6.211537,No
23,41.0,Female,170.0,300.0,Low,No,No,No,20.661064,No,...,Yes,NaN,Low,6.438116,Low,317.0,116.0,1.739325,14.225836,No
24,61.0,Male,136.0,223.0,Low,Yes,No,Yes,20.830855,Yes,...,Yes,High,High,8.191687,Medium,102.0,157.0,9.559221,7.093717,No
25,47.0,Male,135.0,206.0,Low,No,No,No,37.351337,NaN,...,No,Medium,High,9.700067,Low,257.0,122.0,12.121839,12.678489,No
26,55.0,Male,159.0,259.0,Low,Yes,No,Yes,19.265130,Yes,...,Yes,Low,High,4.167873,High,180.0,146.0,0.907313,10.103030,No
27,19.0,Female,158.0,228.0,Low,Yes,Yes,Yes,20.050478,Yes,...,Yes,Low,High,8.028281,Low,233.0,126.0,3.197830,5.486386,No
28,77.0,Male,171.0,300.0,Medium,No,Yes,Yes,35.970643,No,...,Yes,High,High,7.135709,Low,176.0,101.0,6.460138,11.933400,No
29,38.0,Female,151.0,185.0,High,Yes,Yes,No,30.253443,No,...,Yes,Low,Low,5.275531,Medium,396.0,95.0,14.375392,18.149652,No
30,50.0,Female,179.0,206.0,Medium,No,Yes,Yes,26.617996,Yes,...,Yes,Low,Medium,5.846273,Low,179.0,151.0,1.437823,18.228093,No
31,29.0,Female,163.0,278.0,Low,Yes,Yes,Yes,30.175866,Yes,...,Yes,NaN,Medium,9.022903,Low,292.0,90.0,11.453769,15.900844,No
32,75.0,Male,128.0,152.0,High,Yes,No,Yes,37.332449,Yes,...,No,Low,Low,7.521389,Medium,300.0,104.0,9.172698,NaN,No
33,39.0,Male,146.0,163.0,High,No,Yes,Yes,34.656911,Yes,...,Yes,Low,High,4.087182,Low,220.0,96.0,6.305143,10.188311,No
34,78.0,Male,165.0,183.0,High,Yes,No,Yes,33.215362,Yes,...,No,High,Low,9.792168,Medium,341.0,129.0,4.397678,5.460017,No
35,61.0,Female,171.0,219.0,Medium,No,Yes,No,39.491483,Yes,...,Yes,High,Low,7.997106,High,277.0,94.0,5.622685,15.825645,No
36,42.0,Male,152.0,218.0,High,Yes,No,No,29.468749,Yes,...,No,High,Medium,6.655857,High,176.0,86.0,6.343251,18.666259,No
37,66.0,Female,129.0,253.0,Low,No,Yes,No,18.139130,No,...,No,NaN,Low,8.274001,High,248.0,101.0,13.131432,13.770121,No
38,44.0,Male,136.0,178.0,Low,No,No,No,27.438723,No,...,No,High,High,5.227414,High,170.0,111.0,14.789578,19.976343,No
39,76.0,Male,168.0,197.0,Medium,Yes,No,No,20.124583,No,...,Yes,Low,Low,5.562804,High,250.0,94.0,14.350022,14.770823,No
40,80.0,Female,168.0,243.0,Medium,Yes,Yes,No,20.561983,No,...,No,NaN,Medium,4.912758,Medium,388.0,89.0,2.194261,7.409747,No
41,59.0,Female,155.0,228.0,Low,No,No,Yes,23.607820,No,...,No,Medium,High,6.382438,Medium,292.0,84.0,0.435163,12.566270,No
42,45.0,Male,136.0,266.0,Medium,No,No,Yes,26.390078,Yes,...,Yes,Medium,Medium,9.428202,Low,120.0,160.0,3.191830,13.464585,No
43,77.0,Male,137.0,293.0,High,No,Yes,Yes,28.595191,Yes,...,Yes,Medium,High,6.331542,Low,268.0,85.0,4.554322,16.650030,No
44,33.0,Male,171.0,287.0,Medium,No,NaN,No,21.736041,Yes,...,Yes,High,High,5.728514,High,329.0,82.0,6.892172,14.980571,No
45,32.0,Female,142.0,296.0,High,Yes,No,Yes,24.857848,No,...,No,NaN,Medium,8.221383,High,184.0,110.0,7.686827,5.771931,No
46,79.0,Female,153.0,216.0,High,Yes,Yes,Yes,24.083867,No,...,Yes,Medium,Medium,9.217634,Low,342.0,122.0,5.560868,8.151617,No
47,79.0,Male,127.0,281.0,High,Yes,No,No,26.035444,Yes,...,No,Low,Low,5.465393,High,377.0,151.0,13.859583,5.867292,No
48,64.0,Male,132.0,224.0,High,Yes,No,No,20.375792,Yes,...,No,NaN,Low,8.847530,Medium,152.0,112.0,10.873775,11.704411,No
49,79.0,Female,142.0,177.0,High,Yes,No,No,26.741501,No,...,Yes,High,High,5.828829,Medium,378.0,102.0,10.414930,11.142440,No

In [13]:
df.head(100).tail(50)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
50,68.0,Male,176.0,270.0,Low,No,No,No,30.195711,No,...,Yes,Medium,High,5.483897,High,121.0,122.0,8.657694,12.219138,No
51,61.0,Female,173.0,158.0,Low,No,Yes,No,20.132859,Yes,...,No,Medium,High,6.837741,Medium,197.0,91.0,8.371622,19.993292,No
52,72.0,Female,139.0,283.0,Low,Yes,Yes,Yes,29.456945,Yes,...,No,Medium,High,4.400385,Low,338.0,89.0,6.472371,5.364692,No
53,69.0,Female,141.0,272.0,High,Yes,Yes,Yes,34.630083,Yes,...,Yes,NaN,Low,9.173418,Medium,187.0,112.0,6.590294,19.468717,No
54,74.0,Female,166.0,198.0,Medium,No,Yes,No,18.181273,No,...,No,NaN,Low,9.246044,High,399.0,92.0,14.089583,18.575525,No
55,20.0,Female,171.0,240.0,Medium,Yes,Yes,No,19.045621,Yes,...,Yes,Low,Medium,8.064260,Medium,221.0,127.0,8.819535,9.724373,No
56,54.0,Female,142.0,274.0,High,Yes,Yes,No,28.262434,Yes,...,Yes,NaN,Low,5.817312,High,130.0,85.0,6.223301,18.622696,No
57,68.0,Male,160.0,225.0,Medium,No,No,No,37.201106,No,...,No,NaN,High,5.000253,High,110.0,103.0,7.345541,11.578776,No
58,24.0,Female,154.0,299.0,High,Yes,No,No,39.951352,No,...,Yes,Low,Low,8.192829,Medium,194.0,106.0,13.941874,16.798297,No
59,38.0,Female,122.0,253.0,Medium,Yes,No,Yes,20.054664,Yes,...,No,Medium,High,4.618532,High,151.0,142.0,5.182911,5.040321,No
60,26.0,Male,153.0,298.0,High,Yes,Yes,Yes,18.403523,No,...,No,Medium,Medium,6.466650,NaN,124.0,103.0,14.963064,18.552265,No
61,56.0,Female,152.0,182.0,Medium,Yes,Yes,No,23.032938,Yes,...,Yes,NaN,Medium,4.532854,Low,176.0,134.0,5.815515,14.370271,No
62,35.0,Male,165.0,202.0,Medium,No,No,No,28.284345,No,...,No,Low,Low,6.558741,High,179.0,89.0,11.882911,7.147866,No
63,21.0,Female,136.0,189.0,Low,Yes,No,No,30.579510,Yes,...,Yes,Medium,Low,4.806966,High,143.0,99.0,1.020520,18.730315,No
64,42.0,Male,164.0,167.0,Medium,Yes,Yes,No,39.416668,Yes,...,Yes,High,Medium,4.193105,High,240.0,101.0,6.135220,5.631300,No
65,77.0,Male,138.0,162.0,Medium,No,No,Yes,37.546201,No,...,Yes,High,High,6.698406,Low,118.0,124.0,2.199888,5.374928,No
66,31.0,Female,149.0,223.0,High,No,Yes,No,30.366171,Yes,...,Yes,Low,Low,7.406163,Medium,288.0,131.0,4.377274,19.036353,No
67,67.0,Female,142.0,245.0,Medium,No,No,No,25.957705,Yes,...,Yes,Low,Medium,6.636047,Medium,319.0,98.0,6.076762,13.277826,No
68,75.0,Female,134.0,254.0,Medium,Yes,Yes,No,25.068537,No,...,Yes,NaN,High,5.056886,Low,253.0,97.0,8.396500,6.499455,No
69,26.0,Female,178.0,280.0,Medium,No,No,Yes,30.597743,No,...,Yes,High,Low,4.464588,High,396.0,159.0,2.090207,6.649112,No
70,43.0,Male,176.0,299.0,Medium,No,Yes,Yes,33.869763,No,...,Yes,Medium,Low,4.758202,Low,NaN,153.0,6.652325,16.087736,No
71,70.0,Male,133.0,216.0,Medium,Yes,No,No,28.596648,No,...,Yes,Low,High,8.362684,Medium,269.0,127.0,13.970512,13.797857,No
72,19.0,Male,121.0,182.0,Low,No,Yes,No,24.696773,No,...,No,High,Medium,4.095257,High,278.0,149.0,7.613544,13.183163,No
73,37.0,Female,158.0,151.0,Medium,Yes,No,Yes,31.489638,No,...,Yes,Medium,High,9.179898,Medium,308.0,126.0,1.016185,15.017551,No
74,45.0,Male,168.0,224.0,High,Yes,No,No,30.274724,No,...,Yes,High,High,9.040535,Low,224.0,92.0,2.946631,15.446409,No
75,64.0,Female,137.0,223.0,High,Yes,No,Yes,27.402104,No,...,No,Medium,Low,9.282813,Low,217.0,87.0,12.021961,9.291516,No
76,77.0,Female,125.0,284.0,Medium,No,Yes,No,34.463827,Yes,...,No,High,Low,9.272472,High,362.0,84.0,4.585121,19.947671,No
77,24.0,Male,178.0,292.0,Medium,Yes,No,Yes,24.208865,Yes,...,No,Medium,Medium,8.005093,Low,123.0,147.0,12.735843,5.957887,No
78,61.0,Female,151.0,175.0,Medium,No,No,Yes,28.668350,No,...,Yes,Medium,High,9.084585,Low,116.0,114.0,4.513933,16.728706,No
79,78.0,Male,140.0,288.0,Low,No,Yes,No,38.687470,No,...,Yes,Low,Low,8.381982,High,285.0,94.0,8.385896,8.923250,No
80,25.0,Female,159.0,277.0,High,Yes,No,No,33.902231,Yes,...,No,Medium,Medium,5.800725,Low,369.0,114.0,8.791046,18.305997,No
81,64.0,Male,147.0,176.0,Low,Yes,No,Yes,26.535382,No,...,Yes,Low,High,8.530763,High,231.0,154.0,9.804707,6.843418,No
82,52.0,Female,146.0,284.0,Low,No,No,No,30.015910,Yes,...,No,High,Low,7.693459,Low,307.0,112.0,11.132102,19.848357,No
83,31.0,Male,121.0,278.0,Medium,Yes,No,No,26.920602,Yes,...,No,NaN,Medium,4.164940,Low,375.0,119.0,14.938232,12.078993,No
84,34.0,Male,152.0,170.0,Medium,No,No,No,20.476056,No,...,Yes,NaN,Low,8.718157,Low,148.0,147.0,0.102374,10.711593,No
85,53.0,Female,135.0,228.0,High,No,No,No,25.368618,Yes,...,No,High,Medium,9.225010,Low,245.0,139.0,11.630715,6.672780,No
86,67.0,Female,NaN,243.0,Medium,No,No,Yes,36.929749,Yes,...,Yes,Low,Medium,7.104835,Medium,383.0,100.0,11.984273,10.168021,No
87,57.0,Male,141.0,157.0,High,No,Yes,Yes,28.146444,No,...,Yes,NaN,High,6.922160,High,152.0,146.0,3.204095,8.649743,No
88,21.0,Female,175.0,232.0,Low,No,No,Yes,30.862025,Yes,...,Yes,NaN,Low,6.563622,Low,111.0,114.0,4.130554,19.125699,No
89,19.0,Female,162.0,152.0,High,No,Yes,No,21.991829,Yes,...,No,Medium,Medium,8.313009,High,212.0,80.0,8.986875,14.950923,No
90,79.0,Female,166.0,204.0,High,Yes,No,No,25.837089,Yes,...,Yes,Low,High,5.292722,High,183.0,97.0,3.152994,10.284381,No
91,23.0,Male,132.0,292.0,High,No,Yes,No,38.442510,Yes,...,Yes,Low,Low,8.643607,Medium,296.0,85.0,9.038405,6.393442,No
92,71.0,Male,175.0,185.0,Low,No,Yes,No,24.913401,Yes,...,Yes,Medium,High,5.754060,Low,285.0,98.0,2.716786,12.472482,No
93,59.0,Female,121.0,155.0,Low,Yes,No,Yes,23.512343,No,...,No,High,High,5.568983,Low,391.0,110.0,8.321135,16.381444,No
94,21.0,Female,133.0,270.0,Medium,Yes,Yes,No,19.229796,No,...,No,NaN,Low,8.855077,Medium,110.0,127.0,NaN,17.458114,No
95,71.0,Male,175.0,191.0,Medium,No,No,Yes,20.139078,Yes,...,No,Medium,Medium,5.046254,Low,214.0,139.0,14.607872,13.090316,No
96,46.0,Female,157.0,199.0,High,No,Yes,No,30.865365,Yes,...,No,High,High,9.175115,Medium,387.0,135.0,6.625785,19.917059,No
97,80.0,Male,160.0,261.0,High,No,Yes,Yes,32.520722,No,...,No,High,Low,9.867194,Low,228.0,128.0,5.408203,11.780861,No
98,35.0,Female,147.0,295.0,Low,Yes,Yes,No,32.114771,No,...,No,Low,Low,5.919242,Medium,249.0,87.0,12.008687,6.228262,No
99,43.0,Female,126.0,199.0,Low,No,Yes,Yes,29.876245,No,...,No,High,Low,9.567242,Medium,274.0,149.0,3.981062,9.344112,No

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [15]:
df.describe()

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
count,9971.000000,9981.000000,9970.000000,9978.000000,9975.000000,9974.000000,9978.000000,9974.000000,9980.000000
mean,49.296259,149.757740,225.425577,29.077269,6.991329,250.734409,120.142213,7.472201,12.456271
std,18.193970,17.572969,43.575809,6.307098,1.753195,87.067226,23.584011,4.340248,4.323426
min,18.000000,120.000000,150.000000,18.002837,4.000605,100.000000,80.000000,0.003647,5.000236
25%,34.000000,134.000000,187.000000,23.658075,5.449866,176.000000,99.000000,3.674126,8.723334
50%,49.000000,150.000000,226.000000,29.079492,7.003252,250.000000,120.000000,7.472164,12.409395
75%,65.000000,165.000000,263.000000,34.520015,8.531577,326.000000,141.000000,11.255592,16.140564
max,80.000000,180.000000,300.000000,39.996954,9.999952,400.000000,160.000000,14.997087,19.999037

In [16]:
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [17]:
df.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='object')

In [23]:
df['Age']

0       56.0
1       69.0
2       46.0
3       32.0
4       60.0
        ...
9995    25.0
9996    38.0
9997    73.0
9998    23.0
9999    38.0
Name: Age, Length: 10000, dtype: float64

In [34]:
df.select_dtypes('float')

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
0,56.0,153.0,155.0,24.991591,7.633228,342.0,NaN,12.969246,12.387250
1,69.0,146.0,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,46.0,126.0,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,32.0,122.0,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,60.0,166.0,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887
...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,18.788791,6.834954,343.0,133.0,3.588814,19.132004
9996,38.0,172.0,154.0,31.856801,8.247784,377.0,83.0,2.658267,9.715709
9997,73.0,152.0,201.0,26.899911,4.436762,248.0,88.0,4.408867,9.492429
9998,23.0,142.0,299.0,34.964026,8.526329,113.0,153.0,7.215634,11.873486
9999,38.0,128.0,193.0,25.111295,5.659394,121.0,149.0,14.387810,6.208531

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [39]:
df.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

In [40]:
def con_int(x):
    return int(x)

In [41]:
temp = df.select_dtypes('float')

In [42]:
temp.applymap(con_int)

C:\Users\Dppzee\AppData\Local\Temp\ipykernel_4972\199074381.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  temp.applymap(con_int)

ValueError: cannot convert float NaN to integer

In [43]:
temp

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
0,56.0,153.0,155.0,24.991591,7.633228,342.0,NaN,12.969246,12.387250
1,69.0,146.0,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,46.0,126.0,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,32.0,122.0,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,60.0,166.0,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887
...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,18.788791,6.834954,343.0,133.0,3.588814,19.132004
9996,38.0,172.0,154.0,31.856801,8.247784,377.0,83.0,2.658267,9.715709
9997,73.0,152.0,201.0,26.899911,4.436762,248.0,88.0,4.408867,9.492429
9998,23.0,142.0,299.0,34.964026,8.526329,113.0,153.0,7.215634,11.873486
9999,38.0,128.0,193.0,25.111295,5.659394,121.0,149.0,14.387810,6.208531

In [44]:
temp.dropna(inplace=True)

In [45]:
temp

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
1,69.0,146.0,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,46.0,126.0,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,32.0,122.0,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,60.0,166.0,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887
5,25.0,152.0,257.0,28.144681,5.504876,126.0,91.0,4.297575,10.815983
...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,18.788791,6.834954,343.0,133.0,3.588814,19.132004
9996,38.0,172.0,154.0,31.856801,8.247784,377.0,83.0,2.658267,9.715709
9997,73.0,152.0,201.0,26.899911,4.436762,248.0,88.0,4.408867,9.492429
9998,23.0,142.0,299.0,34.964026,8.526329,113.0,153.0,7.215634,11.873486
9999,38.0,128.0,193.0,25.111295,5.659394,121.0,149.0,14.387810,6.208531

In [50]:
def minus(element):
    return element-2

In [51]:
temp['Age'].apply(minus)

1       67.0
2       44.0
3       30.0
4       58.0
5       23.0
        ...
9995    23.0
9996    36.0
9997    71.0
9998    21.0
9999    36.0
Name: Age, Length: 9781, dtype: float64

In [57]:
df.select_dtypes('O')

,Gender,Exercise Habits,Smoking,Family Heart Disease,Diabetes,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sugar Consumption,Heart Disease Status
0,Male,High,Yes,Yes,No,Yes,Yes,No,High,Medium,Medium,No
1,Female,High,No,Yes,Yes,No,Yes,No,Medium,High,Medium,No
2,Male,Low,No,No,No,No,Yes,Yes,Low,Low,Low,No
3,Female,High,Yes,Yes,No,Yes,No,Yes,Low,High,High,No
4,Male,Low,Yes,Yes,Yes,Yes,No,No,Low,High,High,No
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Female,Medium,Yes,No,No,Yes,No,Yes,Medium,High,Medium,Yes
9996,Male,Medium,No,No,No,Yes,No,Yes,NaN,High,Low,Yes
9997,Male,High,Yes,No,Yes,No,Yes,Yes,NaN,Low,Low,Yes
9998,Male,Low,Yes,No,Yes,Yes,No,Yes,Medium,High,Medium,Yes
9999,Female,Medium,Yes,Yes,Yes,No,Yes,Yes,High,Medium,High,Yes

In [60]:
df['Gender_updated']=df['Gender'].map({'Male':0,'Female':1})

In [61]:
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Gender_updated
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,0.0
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,1.0
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No,0.0
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No,1.0
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes,1.0
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes,0.0
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes,0.0
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes,0.0
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes,1.0

In [72]:
temp.drop(columns=['Age', 'Blood Pressure'])

,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
1,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887
5,257.0,28.144681,5.504876,126.0,91.0,4.297575,10.815983
...,...,...,...,...,...,...,...
9995,243.0,18.788791,6.834954,343.0,133.0,3.588814,19.132004
9996,154.0,31.856801,8.247784,377.0,83.0,2.658267,9.715709
9997,201.0,26.899911,4.436762,248.0,88.0,4.408867,9.492429
9998,299.0,34.964026,8.526329,113.0,153.0,7.215634,11.873486
9999,193.0,25.111295,5.659394,121.0,149.0,14.387810,6.208531

In [66]:
temp

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
1,69.0,146.0,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,46.0,126.0,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,32.0,122.0,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,60.0,166.0,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887
5,25.0,152.0,257.0,28.144681,5.504876,126.0,91.0,4.297575,10.815983
...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,18.788791,6.834954,343.0,133.0,3.588814,19.132004
9996,38.0,172.0,154.0,31.856801,8.247784,377.0,83.0,2.658267,9.715709
9997,73.0,152.0,201.0,26.899911,4.436762,248.0,88.0,4.408867,9.492429
9998,23.0,142.0,299.0,34.964026,8.526329,113.0,153.0,7.215634,11.873486
9999,38.0,128.0,193.0,25.111295,5.659394,121.0,149.0,14.387810,6.208531

In [67]:
df.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status',
       'Gender_updated'],
      dtype='object')

In [73]:
df.drop([2,3,4,5],inplace=True)

In [74]:
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Gender_updated
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,0.0
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,1.0
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,...,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No,1.0
7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,No,...,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No,1.0
8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,Yes,...,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes,1.0
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes,0.0
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes,0.0
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes,0.0
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes,1.0

In [78]:
df.sort_values('Age',ascending=True)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Gender_updated
3236,18.0,Female,153.0,253.0,Low,Yes,No,No,26.522315,No,...,NaN,Medium,9.575884,Medium,379.0,101.0,11.480786,9.953602,No,1.0
3723,18.0,Female,152.0,265.0,High,Yes,Yes,No,36.449587,No,...,Medium,Medium,6.543085,Low,256.0,139.0,6.149359,14.296027,No,1.0
5633,18.0,Female,150.0,281.0,High,Yes,Yes,No,32.921497,Yes,...,High,Medium,5.717311,High,174.0,127.0,11.101175,8.673891,No,1.0
5619,18.0,Female,163.0,265.0,Medium,Yes,Yes,Yes,22.608153,No,...,Medium,Medium,6.305006,Low,282.0,143.0,13.948725,9.416863,No,1.0
5617,18.0,Female,141.0,299.0,Medium,No,No,No,27.554749,No,...,Low,High,5.570177,High,158.0,142.0,8.250325,5.164054,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7781,NaN,Male,170.0,297.0,High,Yes,Yes,Yes,29.746500,No,...,Medium,Medium,9.608564,High,198.0,152.0,1.236847,5.419517,No,0.0
8096,NaN,Female,167.0,255.0,Low,Yes,No,Yes,21.170543,Yes,...,High,Low,5.814622,Low,259.0,146.0,13.834235,6.571731,Yes,1.0
9192,NaN,Male,153.0,234.0,High,Yes,Yes,No,35.182266,Yes,...,Low,Low,7.083403,Low,387.0,122.0,9.533345,18.100440,Yes,0.0
9268,NaN,Female,139.0,184.0,High,No,No,Yes,39.398573,No,...,NaN,Low,5.868419,High,122.0,132.0,12.774543,9.703906,Yes,1.0
9835,NaN,Female,176.0,230.0,Low,Yes,Yes,No,30.283088,Yes,...,Medium,Medium,4.333238,Medium,191.0,158.0,11.919513,14.096972,Yes,1.0

In [79]:
df.reset_index()

,index,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Gender_updated
0,0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,0.0
1,1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,1.0
2,6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,...,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No,1.0
3,7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,...,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No,1.0
4,8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,...,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9991,9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,...,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes,1.0
9992,9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,...,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes,0.0
9993,9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,...,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes,0.0
9994,9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,...,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes,0.0
9995,9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,...,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes,1.0

In [80]:
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status,Gender_updated
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No,0.0
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No,1.0
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,...,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No,1.0
7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,No,...,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No,1.0
8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,Yes,...,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,...,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes,1.0
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,...,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes,0.0
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,...,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes,0.0
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,...,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes,0.0
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,...,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes,1.0